---
abstract: 'For automated file archiving with Git'
author:
  - 'Dominic Humphries <dominic@oneandoneis2.com>'
build_requires:
  Data::Dumper: 0
  File::Path: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Git-Archive
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Git::Repository: 0
  IPC::Cmd: 0
  perl: v5.10.0
  strict: 0
resources:
  bugtracker: https://github.com/oneandoneis2/Git-Archive/issues
  homepage: https://github.com/oneandoneis2/Git-Archive
  repository: https://github.com/oneandoneis2/Git-Archive.git
version: 0.09
